# Internal Vortex standard column names
DATE_TIME_COLUMN = 'DATETIME'
OPEN_COLUMN = "Open"
HIGH_COLUMN = "High"
LOW_COLUMN = "Low"
CLOSE_COLUMN = "Close"
VOLUME_COLUMN = "Volume"

# Standard OHLCV sets for validation
STANDARD_OHLCV_COLUMNS = [OPEN_COLUMN, HIGH_COLUMN, LOW_COLUMN, CLOSE_COLUMN, VOLUME_COLUMN]
REQUIRED_PRICE_COLUMNS = [DATE_TIME_COLUMN] + STANDARD_OHLCV_COLUMNS
