# Vortex Financial Data Automation - Root-less Docker Compose Configuration
#
# This docker-compose.yml provides a secure containerized setup for Vortex
# using security best practices with non-root execution throughout.
#
# Quick Start (Free Data with Yahoo Finance):
#   docker-compose up -d
#   
# The container will automatically:
#   - Run entirely as vortex user (UID 1000) - NO ROOT PRIVILEGES
#   - Use Yahoo Finance (free, no setup required)
#   - Download data to ./data directory
#   - Run on schedule using supervisord (not system cron)
#
# Configuration Options (Choose One):
#
# Option 1: TOML Configuration (RECOMMENDED - More Convenient)
#   1. Create config/config.toml with your settings:
#      [general]
#      default_provider = "barchart"
#      backup_enabled = true
#      
#      [providers.barchart]
#      username = "your_email@example.com"
#      password = "your_password"
#      daily_limit = 200
#   
#   2. Run: docker-compose up -d
#
# Option 2: Environment Variables (.env file)
#   1. Create .env file:
#      VORTEX_DEFAULT_PROVIDER=barchart
#      VORTEX_BARCHART_USERNAME=your_email@example.com
#      VORTEX_BARCHART_PASSWORD=your_password
#   2. Uncomment the environment variables in this file
#   3. Run: docker-compose up -d
#
# Custom Assets:
#   1. Create config/assets.json with your instruments  
#   2. Mount it: uncomment the custom assets volume below
#
# Monitoring:
#   - Logs: docker-compose logs -f vortex
#   - Health: docker-compose ps
#   - Data: check ./data directory
#
services:
  vortex:
    build:
      context: ..
      dockerfile: docker/Dockerfile  # Use main Dockerfile (now root-less by default)
    container_name: vortex
    restart: unless-stopped
    
    # Security: Container runs as vortex user (UID 1000) by default from Dockerfile
    # No user override needed - Dockerfile already sets USER vortex
    
    environment:
      # Container-specific settings (keep these as environment variables)
      # Output directory (container path)
      VORTEX_OUTPUT_DIR: /data
      
      # Container runtime settings
      VORTEX_SCHEDULE: ${VORTEX_SCHEDULE:-0 8 * * *}  # Cron schedule
      VORTEX_RUN_ON_STARTUP: ${VORTEX_RUN_ON_STARTUP:-true}
      VORTEX_DOWNLOAD_ARGS: ${VORTEX_DOWNLOAD_ARGS:---yes}
      
      # Application configuration (RECOMMENDED: Use config/config.toml instead)
      # Uncomment these if you prefer environment variables over TOML config
      # VORTEX_DEFAULT_PROVIDER: ${VORTEX_DEFAULT_PROVIDER:-yahoo}
      # VORTEX_LOG_LEVEL: ${VORTEX_LOG_LEVEL:-INFO}
      # VORTEX_LOGGING_FORMAT: ${VORTEX_LOGGING_FORMAT:-console}
      # VORTEX_BACKUP_ENABLED: ${VORTEX_BACKUP_ENABLED:-false}
      # 
      # # Provider credentials (RECOMMENDED: Use config/config.toml instead)
      # VORTEX_BARCHART_USERNAME: ${VORTEX_BARCHART_USERNAME:-}
      # VORTEX_BARCHART_PASSWORD: ${VORTEX_BARCHART_PASSWORD:-}
      # VORTEX_BARCHART_DAILY_LIMIT: ${VORTEX_BARCHART_DAILY_LIMIT:-150}
      # 
      # # Interactive Brokers configuration (RECOMMENDED: Use config/config.toml instead)  
      # VORTEX_IBKR_HOST: ${VORTEX_IBKR_HOST:-localhost}
      # VORTEX_IBKR_PORT: ${VORTEX_IBKR_PORT:-7497}
      # VORTEX_IBKR_CLIENT_ID: ${VORTEX_IBKR_CLIENT_ID:-1}
    
    volumes:
      # Data output directory - where downloaded CSV/Parquet files are stored
      - ${DATA_DIR:-./data}:/data
      
      # Configuration directory - vortex user's config location
      - ${CONFIG_DIR:-./config}:/home/vortex/.config/vortex
      
      # Optional: Mount custom assets file directly
      # - ./my-assets.json:/app/config/assets/custom.json:ro
      
      # Optional: Mount logs directory
      # - ${LOGS_DIR:-./logs}:/var/log/supervisor
    
    # Health check using modern CLI (runs as vortex user)
    healthcheck:
      test: ["CMD-SHELL", "vortex config --show > /dev/null || exit 1"]
      interval: 1h
      timeout: 30s
      retries: 3
      start_period: 30s
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Optional: Add database for storing metadata
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: vortex
  #     POSTGRES_USER: vortex
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: